// <auto-generated />
using System;
using DailyNews.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyNews.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    [Migration("20260726210821_UpdateFilmFestivalContent")]
    partial class UpdateFilmFestivalContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("DailyNews.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Developer",
                            Name = "Hossein Jafari Sharami"
                        });
                });

            modelBuilder.Entity("DailyNews.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Politics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Economy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Culture"
                        });
                });

            modelBuilder.Entity("DailyNews.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            Content = "In the latest political news...",
                            PublishDate = new DateTime(2026, 2, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "New Political Developments in the Country"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            CategoryId = 1,
                            Content = "Lawmakers spent hours reviewing the proposed budget...",
                            PublishDate = new DateTime(2026, 2, 7, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Parliament Debates New Budget Proposal"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            CategoryId = 1,
                            Content = "Talks focused on trade and regional stability...",
                            PublishDate = new DateTime(2026, 2, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Foreign Minister Meets Regional Leaders"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            CategoryId = 1,
                            Content = "The new rules aim to improve transparency...",
                            PublishDate = new DateTime(2026, 2, 14, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            Title = "Election Commission Announces New Guidelines"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 1,
                            CategoryId = 1,
                            Content = "Analysts are divided on what the changes mean...",
                            PublishDate = new DateTime(2026, 2, 18, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cabinet Reshuffle Sparks Public Debate"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            CategoryId = 2,
                            Content = "The dollar reached a new record...",
                            PublishDate = new DateTime(2026, 2, 3, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Exchange Rate Rises in the Market"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 1,
                            CategoryId = 2,
                            Content = "The decision comes amid ongoing inflation concerns...",
                            PublishDate = new DateTime(2026, 2, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Central Bank Adjusts Interest Rates"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 1,
                            CategoryId = 2,
                            Content = "Consumer prices rose at their slowest pace since last year...",
                            PublishDate = new DateTime(2026, 2, 11, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inflation Slows for Third Straight Month"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 1,
                            CategoryId = 2,
                            Content = "Investors reacted positively to the latest earnings reports...",
                            PublishDate = new DateTime(2026, 2, 15, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Stock Market Reaches Record High"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 1,
                            CategoryId = 2,
                            Content = "New job figures beat analyst expectations...",
                            PublishDate = new DateTime(2026, 2, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Unemployment Rate Drops to New Low"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            CategoryId = 3,
                            Content = "The players shone...",
                            PublishDate = new DateTime(2026, 2, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "National Team Wins Friendly Match"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 1,
                            CategoryId = 3,
                            Content = "A last-minute goal secured their place in the final...",
                            PublishDate = new DateTime(2026, 2, 9, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Local Club Advances to Cup Final"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 1,
                            CategoryId = 3,
                            Content = "The deal keeps him at the club for another three years...",
                            PublishDate = new DateTime(2026, 2, 12, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Striker Signs New Contract"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 1,
                            CategoryId = 3,
                            Content = "Thousands took part in this year's event...",
                            PublishDate = new DateTime(2026, 2, 16, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Marathon Draws Record Number of Runners"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 1,
                            CategoryId = 3,
                            Content = "The young squad impressed fans throughout the tournament...",
                            PublishDate = new DateTime(2026, 2, 20, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Youth Team Claims Regional Championship"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 1,
                            CategoryId = 4,
                            Content = "The exhibition features works from local artists...",
                            PublishDate = new DateTime(2026, 2, 6, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "New Exhibition Opens at City Museum"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 1,
                            CategoryId = 4,
                            Content = "Organizers revealed the full schedule today, unveiling a lineup that spans more than sixty films from over twenty countries. The festival, now in its twelfth year, has grown steadily from a small local gathering into one of the region's most anticipated cultural events. This year's opening night will feature a much-anticipated drama exploring themes of memory and displacement, followed by a reception where attendees can meet the cast and director. Throughout the week, the festival will host a mix of feature films, documentaries, and short film showcases, with several sessions dedicated entirely to first-time directors. A retrospective section will honor a celebrated filmmaker whose career spans four decades, screening restored prints of several early works alongside newer releases. Panel discussions are scheduled daily, bringing together critics, actors, and industry professionals to talk about everything from independent financing to the future of streaming. The festival has also expanded its educational outreach this year, offering free workshops for students interested in screenwriting and cinematography. Organizers say ticket demand has already exceeded last year's numbers, with several premiere screenings selling out within hours of going on sale. A closing night award ceremony will recognize the best entries across multiple categories, chosen by a jury of respected filmmakers and critics. Local businesses have also reported an uptick in interest tied to the festival, with several restaurants and hotels offering special packages for attendees. Festival organizers hope this year's edition will further cement the city's reputation as a growing hub for independent cinema.",
                            PublishDate = new DateTime(2026, 2, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Film Festival Announces This Year's Lineup"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 1,
                            CategoryId = 4,
                            Content = "The century-old building has been fully restored...",
                            PublishDate = new DateTime(2026, 2, 17, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Historic Theater Reopens After Renovation"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 1,
                            CategoryId = 4,
                            Content = "The novel has been praised for its vivid storytelling...",
                            PublishDate = new DateTime(2026, 2, 21, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Local Author Wins National Book Award"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 1,
                            CategoryId = 4,
                            Content = "The annual festival celebrated regional musical heritage...",
                            PublishDate = new DateTime(2026, 2, 24, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Traditional Music Festival Draws Thousands"
                        });
                });

            modelBuilder.Entity("DailyNews.Models.News", b =>
                {
                    b.HasOne("DailyNews.Models.Author", "Author")
                        .WithMany("News")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyNews.Models.Category", "Category")
                        .WithMany("News")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DailyNews.Models.Author", b =>
                {
                    b.Navigation("News");
                });

            modelBuilder.Entity("DailyNews.Models.Category", b =>
                {
                    b.Navigation("News");
                });
#pragma warning restore 612, 618
        }
    }
}
